[tool.poetry]
name = "repl_python3_42Game1"
version = "0.1.0"
description = ""
authors = ["wwwwelton <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
arcade = "^2.6.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
